import { createApp } from "vue";
// import STable from '@surely-vue/table';
// import '@surely-vue/table/dist/index.less';
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import "vx-easyui/dist/themes/default/easyui.css";
import "vx-easyui/dist/themes/icon.css";
// import 'vx-easyui/dist/themes/vue.css';
import EasyUI from "vx-easyui";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import Antd from "ant-design-vue";
import "@/style/public.css";
const app = createApp(App);
app.use(store);
app.use(router);
app.use(Antd);
app.use(ElementPlus);
// app.use(EasyUI);
app.mount("#app");
// createApp(App).use(store).use(router).use(Antd).use(ElementPlus).mount("#app");
